### ISSUE TITLE
Second start of program causes a NullPointerException

### ISSUE THREAD

**Issue by Bauepete** [Bauepete/no-beard#3]
After a first run of a program, when hitting the Run-Button again, the following output is in the console:
Starting programm at pc 0
RUNTIME: 1024: Address 0x400 cannot be accessed in program memory
Exception in thread "Thread-6" java.lang.NullPointerException
	at machine.ControlUnit.executeCycle(ControlUnit.java:114)
	at machine.NoBeardMachine.step(NoBeardMachine.java:98)
	at machine.NoBeardMachine.runProgram(NoBeardMachine.java:93)
	at nbmgui.Controller$1.run(Controller.java:74)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Bauepete** [comment]
After a bit of analysis it turned out that this is a problem in the core. Changed project and assignee.
